/* Generated by Yosys 0.45+217 (git sha1 380a42559, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module elevator(request_floor, in_current_floor, clk, reset, complete, direction, over_time, over_weight, weight_alert, door_alert, out_current_floor);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  input clk;
  wire clk;
  output complete;
  wire complete;
  output direction;
  wire direction;
  output door_alert;
  wire door_alert;
  input [7:0] in_current_floor;
  wire [7:0] in_current_floor;
  output [7:0] out_current_floor;
  wire [7:0] out_current_floor;
  input over_time;
  wire over_time;
  input over_weight;
  wire over_weight;
  wire r_complete;
  wire r_direction;
  wire r_door_alert;
  wire [7:0] r_out_current_floor;
  wire r_weight_alert;
  input [7:0] request_floor;
  wire [7:0] request_floor;
  input reset;
  wire reset;
  output weight_alert;
  wire weight_alert;
  INV_X1 _110_ (
    .A(request_floor[6]),
    .ZN(_039_)
  );
  INV_X1 _111_ (
    .A(request_floor[5]),
    .ZN(_040_)
  );
  INV_X1 _112_ (
    .A(request_floor[4]),
    .ZN(_041_)
  );
  INV_X1 _113_ (
    .A(request_floor[3]),
    .ZN(_042_)
  );
  INV_X1 _114_ (
    .A(request_floor[2]),
    .ZN(_043_)
  );
  INV_X1 _115_ (
    .A(r_out_current_floor[6]),
    .ZN(_044_)
  );
  INV_X1 _116_ (
    .A(r_out_current_floor[5]),
    .ZN(_045_)
  );
  INV_X1 _117_ (
    .A(r_out_current_floor[4]),
    .ZN(_046_)
  );
  INV_X1 _118_ (
    .A(r_out_current_floor[3]),
    .ZN(_047_)
  );
  INV_X1 _119_ (
    .A(r_out_current_floor[2]),
    .ZN(_048_)
  );
  INV_X1 _120_ (
    .A(r_out_current_floor[1]),
    .ZN(_049_)
  );
  INV_X1 _121_ (
    .A(r_out_current_floor[0]),
    .ZN(_050_)
  );
  INV_X1 _122_ (
    .A(request_floor[7]),
    .ZN(_051_)
  );
  INV_X1 _123_ (
    .A(r_out_current_floor[7]),
    .ZN(_052_)
  );
  INV_X1 _124_ (
    .A(reset),
    .ZN(_053_)
  );
  AOI22_X1 _125_ (
    .A1(_039_),
    .A2(r_out_current_floor[6]),
    .B1(_051_),
    .B2(r_out_current_floor[7]),
    .ZN(_054_)
  );
  NOR2_X1 _126_ (
    .A1(_051_),
    .A2(r_out_current_floor[7]),
    .ZN(_055_)
  );
  XOR2_X1 _127_ (
    .A(request_floor[7]),
    .B(r_out_current_floor[7]),
    .Z(_056_)
  );
  XOR2_X1 _128_ (
    .A(request_floor[6]),
    .B(r_out_current_floor[6]),
    .Z(_057_)
  );
  NOR2_X1 _129_ (
    .A1(_056_),
    .A2(_057_),
    .ZN(_058_)
  );
  AOI22_X1 _130_ (
    .A1(_040_),
    .A2(r_out_current_floor[5]),
    .B1(r_out_current_floor[4]),
    .B2(_041_),
    .ZN(_059_)
  );
  NAND2_X1 _131_ (
    .A1(request_floor[5]),
    .A2(_045_),
    .ZN(_060_)
  );
  NAND2_X1 _132_ (
    .A1(request_floor[4]),
    .A2(_046_),
    .ZN(_061_)
  );
  AND4_X1 _133_ (
    .A1(_058_),
    .A2(_059_),
    .A3(_060_),
    .A4(_061_),
    .ZN(_062_)
  );
  NAND4_X1 _134_ (
    .A1(_058_),
    .A2(_059_),
    .A3(_060_),
    .A4(_061_),
    .ZN(_063_)
  );
  AOI22_X1 _135_ (
    .A1(_042_),
    .A2(r_out_current_floor[3]),
    .B1(r_out_current_floor[2]),
    .B2(_043_),
    .ZN(_064_)
  );
  OAI22_X1 _136_ (
    .A1(request_floor[3]),
    .A2(_047_),
    .B1(_048_),
    .B2(request_floor[2]),
    .ZN(_065_)
  );
  NOR2_X1 _137_ (
    .A1(_042_),
    .A2(r_out_current_floor[3]),
    .ZN(_066_)
  );
  NAND2_X1 _138_ (
    .A1(request_floor[3]),
    .A2(_047_),
    .ZN(_067_)
  );
  XOR2_X1 _139_ (
    .A(request_floor[3]),
    .B(r_out_current_floor[3]),
    .Z(_068_)
  );
  XOR2_X1 _140_ (
    .A(request_floor[2]),
    .B(r_out_current_floor[2]),
    .Z(_069_)
  );
  NOR2_X1 _141_ (
    .A1(_068_),
    .A2(_069_),
    .ZN(_070_)
  );
  OR4_X1 _142_ (
    .A1(request_floor[1]),
    .A2(_049_),
    .A3(_068_),
    .A4(_069_),
    .ZN(_071_)
  );
  XOR2_X1 _143_ (
    .A(request_floor[1]),
    .B(r_out_current_floor[1]),
    .Z(_072_)
  );
  AOI21_X1 _144_ (
    .A(_072_),
    .B1(_050_),
    .B2(request_floor[0]),
    .ZN(_073_)
  );
  AND2_X1 _145_ (
    .A1(_070_),
    .A2(_073_),
    .ZN(_074_)
  );
  AOI22_X1 _146_ (
    .A1(_065_),
    .A2(_067_),
    .B1(_070_),
    .B2(_073_),
    .ZN(_075_)
  );
  OAI21_X1 _147_ (
    .A(_071_),
    .B1(_066_),
    .B2(_064_),
    .ZN(_076_)
  );
  AOI21_X1 _148_ (
    .A(_063_),
    .B1(_071_),
    .B2(_075_),
    .ZN(_077_)
  );
  OAI21_X1 _149_ (
    .A(_062_),
    .B1(_074_),
    .B2(_076_),
    .ZN(_078_)
  );
  NOR2_X1 _150_ (
    .A1(_054_),
    .A2(_055_),
    .ZN(_079_)
  );
  AOI21_X1 _151_ (
    .A(_059_),
    .B1(_045_),
    .B2(request_floor[5]),
    .ZN(_080_)
  );
  NAND2_X1 _152_ (
    .A1(_058_),
    .A2(_060_),
    .ZN(_081_)
  );
  AOI21_X1 _153_ (
    .A(_079_),
    .B1(_080_),
    .B2(_058_),
    .ZN(_082_)
  );
  OAI22_X1 _154_ (
    .A1(_054_),
    .A2(_055_),
    .B1(_059_),
    .B2(_081_),
    .ZN(_083_)
  );
  OR2_X1 _155_ (
    .A1(request_floor[0]),
    .A2(_050_),
    .ZN(_084_)
  );
  NAND3_X1 _156_ (
    .A1(_062_),
    .A2(_074_),
    .A3(_084_),
    .ZN(_085_)
  );
  OAI21_X1 _157_ (
    .A(_085_),
    .B1(_083_),
    .B2(_077_),
    .ZN(_086_)
  );
  NOR3_X1 _158_ (
    .A1(reset),
    .A2(over_time),
    .A3(over_weight),
    .ZN(_087_)
  );
  INV_X1 _159_ (
    .A(_087_),
    .ZN(_088_)
  );
  NOR2_X1 _160_ (
    .A1(_052_),
    .A2(_088_),
    .ZN(_089_)
  );
  OAI211_X1 _161_ (
    .A(_085_),
    .B(_089_),
    .C1(_077_),
    .C2(_083_),
    .ZN(_090_)
  );
  AND4_X1 _162_ (
    .A1(_062_),
    .A2(_074_),
    .A3(_084_),
    .A4(_087_),
    .ZN(_010_)
  );
  NOR2_X1 _163_ (
    .A1(reset),
    .A2(_087_),
    .ZN(_091_)
  );
  NOR2_X1 _164_ (
    .A1(_010_),
    .A2(_091_),
    .ZN(_092_)
  );
  OAI21_X1 _165_ (
    .A(r_out_current_floor[6]),
    .B1(_010_),
    .B2(_091_),
    .ZN(_093_)
  );
  NAND2_X1 _166_ (
    .A1(reset),
    .A2(in_current_floor[6]),
    .ZN(_094_)
  );
  NOR2_X1 _167_ (
    .A1(_045_),
    .A2(_088_),
    .ZN(_095_)
  );
  NAND3_X1 _168_ (
    .A1(_078_),
    .A2(_082_),
    .A3(_087_),
    .ZN(_096_)
  );
  NAND3_X1 _169_ (
    .A1(_078_),
    .A2(_082_),
    .A3(_095_),
    .ZN(_097_)
  );
  NAND4_X1 _170_ (
    .A1(_090_),
    .A2(_093_),
    .A3(_094_),
    .A4(_097_),
    .ZN(_000_)
  );
  NOR2_X1 _171_ (
    .A1(_044_),
    .A2(_088_),
    .ZN(_012_)
  );
  OAI211_X1 _172_ (
    .A(_085_),
    .B(_012_),
    .C1(_077_),
    .C2(_083_),
    .ZN(_013_)
  );
  OAI21_X1 _173_ (
    .A(r_out_current_floor[5]),
    .B1(_010_),
    .B2(_091_),
    .ZN(_014_)
  );
  NAND2_X1 _174_ (
    .A1(reset),
    .A2(in_current_floor[5]),
    .ZN(_015_)
  );
  NOR2_X1 _175_ (
    .A1(_046_),
    .A2(_088_),
    .ZN(_016_)
  );
  NAND3_X1 _176_ (
    .A1(_078_),
    .A2(_082_),
    .A3(_016_),
    .ZN(_017_)
  );
  NAND4_X1 _177_ (
    .A1(_013_),
    .A2(_014_),
    .A3(_015_),
    .A4(_017_),
    .ZN(_001_)
  );
  OAI211_X1 _178_ (
    .A(_085_),
    .B(_095_),
    .C1(_077_),
    .C2(_083_),
    .ZN(_018_)
  );
  NOR2_X1 _179_ (
    .A1(_047_),
    .A2(_088_),
    .ZN(_019_)
  );
  NAND3_X1 _180_ (
    .A1(_078_),
    .A2(_082_),
    .A3(_019_),
    .ZN(_020_)
  );
  NAND2_X1 _181_ (
    .A1(reset),
    .A2(in_current_floor[4]),
    .ZN(_021_)
  );
  OAI21_X1 _182_ (
    .A(r_out_current_floor[4]),
    .B1(_010_),
    .B2(_091_),
    .ZN(_022_)
  );
  NAND4_X1 _183_ (
    .A1(_018_),
    .A2(_020_),
    .A3(_021_),
    .A4(_022_),
    .ZN(_002_)
  );
  OAI211_X1 _184_ (
    .A(_085_),
    .B(_016_),
    .C1(_077_),
    .C2(_083_),
    .ZN(_023_)
  );
  OAI21_X1 _185_ (
    .A(r_out_current_floor[3]),
    .B1(_010_),
    .B2(_091_),
    .ZN(_024_)
  );
  NAND2_X1 _186_ (
    .A1(reset),
    .A2(in_current_floor[3]),
    .ZN(_025_)
  );
  NOR2_X1 _187_ (
    .A1(_048_),
    .A2(_088_),
    .ZN(_026_)
  );
  NAND3_X1 _188_ (
    .A1(_078_),
    .A2(_082_),
    .A3(_026_),
    .ZN(_027_)
  );
  NAND4_X1 _189_ (
    .A1(_023_),
    .A2(_024_),
    .A3(_025_),
    .A4(_027_),
    .ZN(_003_)
  );
  OAI211_X1 _190_ (
    .A(_085_),
    .B(_019_),
    .C1(_077_),
    .C2(_083_),
    .ZN(_028_)
  );
  NAND2_X1 _191_ (
    .A1(r_out_current_floor[1]),
    .A2(_087_),
    .ZN(_029_)
  );
  OR3_X1 _192_ (
    .A1(_077_),
    .A2(_083_),
    .A3(_029_),
    .ZN(_030_)
  );
  NAND2_X1 _193_ (
    .A1(reset),
    .A2(in_current_floor[2]),
    .ZN(_031_)
  );
  OAI21_X1 _194_ (
    .A(r_out_current_floor[2]),
    .B1(_010_),
    .B2(_091_),
    .ZN(_032_)
  );
  NAND4_X1 _195_ (
    .A1(_028_),
    .A2(_030_),
    .A3(_031_),
    .A4(_032_),
    .ZN(_004_)
  );
  NAND4_X1 _196_ (
    .A1(r_out_current_floor[0]),
    .A2(_078_),
    .A3(_082_),
    .A4(_087_),
    .ZN(_033_)
  );
  OAI211_X1 _197_ (
    .A(_085_),
    .B(_026_),
    .C1(_077_),
    .C2(_083_),
    .ZN(_034_)
  );
  NAND2_X1 _198_ (
    .A1(reset),
    .A2(in_current_floor[1]),
    .ZN(_035_)
  );
  OAI21_X1 _199_ (
    .A(r_out_current_floor[1]),
    .B1(_010_),
    .B2(_091_),
    .ZN(_036_)
  );
  NAND4_X1 _200_ (
    .A1(_033_),
    .A2(_034_),
    .A3(_035_),
    .A4(_036_),
    .ZN(_005_)
  );
  NAND2_X1 _201_ (
    .A1(reset),
    .A2(in_current_floor[0]),
    .ZN(_037_)
  );
  OAI221_X1 _202_ (
    .A(_037_),
    .B1(_029_),
    .B2(_086_),
    .C1(_050_),
    .C2(_092_),
    .ZN(_006_)
  );
  NAND2_X1 _203_ (
    .A1(reset),
    .A2(in_current_floor[7]),
    .ZN(_038_)
  );
  OAI221_X1 _204_ (
    .A(_038_),
    .B1(_092_),
    .B2(_052_),
    .C1(_044_),
    .C2(_096_),
    .ZN(_007_)
  );
  NOR3_X1 _205_ (
    .A1(reset),
    .A2(over_time),
    .A3(_087_),
    .ZN(_008_)
  );
  AND2_X1 _206_ (
    .A1(_053_),
    .A2(over_time),
    .ZN(_009_)
  );
  NAND2_X1 _207_ (
    .A1(_053_),
    .A2(_096_),
    .ZN(_011_)
  );
  DFF_X1 _208_ (
    .CK(clk),
    .D(_006_),
    .Q(r_out_current_floor[0]),
    .QN(_103_)
  );
  DFF_X1 _209_ (
    .CK(clk),
    .D(_005_),
    .Q(r_out_current_floor[1]),
    .QN(_104_)
  );
  DFF_X1 _210_ (
    .CK(clk),
    .D(_004_),
    .Q(r_out_current_floor[2]),
    .QN(_105_)
  );
  DFF_X1 _211_ (
    .CK(clk),
    .D(_003_),
    .Q(r_out_current_floor[3]),
    .QN(_106_)
  );
  DFF_X1 _212_ (
    .CK(clk),
    .D(_002_),
    .Q(r_out_current_floor[4]),
    .QN(_107_)
  );
  DFF_X1 _213_ (
    .CK(clk),
    .D(_001_),
    .Q(r_out_current_floor[5]),
    .QN(_108_)
  );
  DFF_X1 _214_ (
    .CK(clk),
    .D(_000_),
    .Q(r_out_current_floor[6]),
    .QN(_109_)
  );
  DFF_X1 _215_ (
    .CK(clk),
    .D(_007_),
    .Q(r_out_current_floor[7]),
    .QN(_102_)
  );
  DFF_X1 _216_ (
    .CK(clk),
    .D(_011_),
    .Q(r_direction),
    .QN(_098_)
  );
  DFF_X1 _217_ (
    .CK(clk),
    .D(_010_),
    .Q(r_complete),
    .QN(_099_)
  );
  DFF_X1 _218_ (
    .CK(clk),
    .D(_009_),
    .Q(r_door_alert),
    .QN(_100_)
  );
  DFF_X1 _219_ (
    .CK(clk),
    .D(_008_),
    .Q(r_weight_alert),
    .QN(_101_)
  );
  assign complete = r_complete;
  assign direction = r_direction;
  assign door_alert = r_door_alert;
  assign out_current_floor = r_out_current_floor;
  assign weight_alert = r_weight_alert;
endmodule
